{% set version = "1.7.2" %}

package:
  name: cdo
  version: {{ version }}

source:
  fn: cdo-{{ version }}.tar.gz
  url: https://code.zmaw.de/attachments/download/12760/cdo-{{ version }}.tar.gz
  sha256: 4c43eba7a95f77457bfe0d30fb82382b3b5f2b0cf90aca6f0f0a008f6cc7e697

build:
  number: 1
  skip: True  # [win]

requirements:
  build:
    - jasper
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - util-linux  # [linux]
    - ecmwf_grib
    - udunits2
    - libxml2 2.9.*
    - fftw
  run:
    - jasper
    - libnetcdf 4.4.*
    - proj4 4.9.3
    - libgcc  # [linux]
    - util-linux  # [linux]
    - ecmwf_grib
    - udunits2
    - libxml2 2.9.*
    - fftw

test:
  commands:
    - cdo -h
    #- conda inspect linkages -p $PREFIX cdo  # [not win]
    #- conda inspect objects -p $PREFIX cdo  # [osx]

about:
  home: https://code.zmaw.de/projects/cdo
  license: GPL-2.0
  summary: 'CLI tools to manipulate and analyse Climate and NWP model Data.'

extra:
  recipe-maintainers:
    - ocefpaf
